substitutions:
  device_name: treatlife-ds02s
  friendly_devicename: Treatlife DS02S Dimmer
  comment: "Treatlife Single Pole Smart Dimmer Switch (DS02S)"
  default_update_interval: 60s

# Esphome core information
esphome:
  name: ${device_name}
  friendly_name: ${friendly_devicename}
  comment: ${comment}
  on_boot:
    then:
      - select.set_index: 
          id: "load_type"
          index: 0
      - select.set_index:
          id: "indicator_led"
          index: 0
  platformio_options: 
    lib_ignore: RPAsyncTCP
    

# The board type for this device
bk72xx:
  board: generic-bk7231t-qfn32-tuya

<<: !include components/api.yaml
<<: !include components/captive_portal.yaml
<<: !include components/logger.yaml
<<: !include components/mdns.yaml
<<: !include components/ota/esphome.yaml
<<: !include components/safe_mode.yaml
<<: !include components/time/sntp-local.yaml
<<: !include components/web_server.yaml
<<: !include components/wifi.yaml

# Loads TUYA library to communicate with MCU and sends the time to the MCU
tuya:
  time_id: sntp_time

# Sets the communication details to MCU
uart:
  rx_pin: GPIO10
  tx_pin: GPIO11
  baud_rate: 115200
  rx_buffer_size: 512

binary_sensor:
  - <<: !include components/binary_sensor/status.yaml

# Main light entity
light:
  - platform: "tuya"
    name: "${friendly_devicename}: Switch"
    id: light_id
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 10
    max_value: 1000
    restore_mode: RESTORE_DEFAULT_OFF

# This allows you to control the Dimming Mode and how the led operates when the load is on or off.
number:
  - platform: "tuya"
    id: min_brightness
    name: "${friendly_devicename}: Min Brightness"
    number_datapoint: 3
    min_value: 10
    max_value: 100
    step: 10
    entity_category: config

# ── Buttons ──────────────────────────────────────────────────
button:
  - platform: restart
    name: "${friendly_devicename}: Reboot"
    entity_category: diagnostic

  - platform: safe_mode
    name: "${friendly_devicename}: Reboot Safe Mode"
    entity_category: diagnostic

select:
  - platform: "tuya"
    id: load_type
    name: "${friendly_devicename}: Load Type"
    enum_datapoint: 4
    options:
      0: "LED"
      1: "Incandescent"
      2: "Halogen"
    entity_category: config

  - platform: "tuya"
    id: indicator_led
    name: "${friendly_devicename}: Indicator Mode"
    int_datapoint: 104
    options:
      0: "Opposite"
      1: "Follow"
    entity_category: config


# Datapoint notes
#1 - switch
#2 - dimmer = 763
#3 - brightness min = 10 Diming Range 1%= 10, 100%=1000
#4 - dimming mode = LED, incandescent, halogen
#101 - led_bright low/ wake_up value=AAAA
#102 - count_down value=0
#103 - bright_value_3 = 10
#104 - led indicator
#105 - random time

sensor:
  - <<: !include components/sensor/wifi_signal.yaml
  - <<: !include components/sensor/uptime.yaml

text_sensor:
  - <<: !include components/text_sensor/wifi_info.yaml