# Beken BK7231N CB3S board — dual-outlet Tuya dimmer plug (DP12).
#
# https://docs.platformio.org/en/latest/boards/espressif8266/esp12e.html
# https://developer.tuya.com/en/docs/iot/cb3s?id=Kai94mec0s076

---
esphome:
  <<: !include "../components/esphome_dp12.yaml"

bk72xx:
  board: cb3s
